//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T4Test002 {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class EffectTemplate : EffectTemplateBase {
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 6 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 7 ""
  
//string[] cruds = new string[] {"Create", "Load", "Update", "Delete"};  \
string[] cruds = new string[] {"Create"}; 
string[] actionTypes = new string[] {"", "Success"};


string EntityClass = entityClassName;
string memberEntity = entityClassName;
string localEntity = entityClassName.ToLower();

   string actionClassName = crud + entityClassName + actionType + "Action"; 
   string effectClassName = crud + entityClassName + actionType + "Effect"; 

            
            #line default
            #line hidden
            
            #line 20 ""
            this.Write("using System.Threading.Tasks;\nusing Fluxor;\nusing Lazorm;\nusing Lazorm.Services;\n" +
                    "using Lazorm.Store.Features.Todos.Actions.UpdateTodo;\nusing Microsoft.Extensions" +
                    ".Logging;\n\nnamespace Lazorm.Store.Features.");
            
            #line default
            #line hidden
            
            #line 27 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( entityClassNamePlural ));
            
            #line default
            #line hidden
            
            #line 27 ""
            this.Write(".Effects\n{\n    public class ");
            
            #line default
            #line hidden
            
            #line 29 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( effectClassName ));
            
            #line default
            #line hidden
            
            #line 29 ""
            this.Write(": Effect<");
            
            #line default
            #line hidden
            
            #line 29 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( actionClassName ));
            
            #line default
            #line hidden
            
            #line 29 ""
            this.Write(">\n    {\n        private readonly ILogger<");
            
            #line default
            #line hidden
            
            #line 31 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( effectClassName ));
            
            #line default
            #line hidden
            
            #line 31 ""
            this.Write("> _logger;\n\n        public ");
            
            #line default
            #line hidden
            
            #line 33 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( effectClassName ));
            
            #line default
            #line hidden
            
            #line 33 ""
            this.Write("(ILogger<");
            
            #line default
            #line hidden
            
            #line 33 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( effectClassName ));
            
            #line default
            #line hidden
            
            #line 33 ""
            this.Write("> logger) =>\n            _logger = logger;\n\n        protected override async Task" +
                    " HandleAsync(");
            
            #line default
            #line hidden
            
            #line 36 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( actionClassName ));
            
            #line default
            #line hidden
            
            #line 36 ""
            this.Write(" action, IDispatcher dispatcher)\n        {\n");
            
            #line default
            #line hidden
            
            #line 38 ""
 if (actionType == "") { 
            
            #line default
            #line hidden
            
            #line 39 ""
 if (crud == "Load" ) { 
            
            #line default
            #line hidden
            
            #line 40 ""
            this.Write("            try\n            {\n                _logger.LogInformation($\"Loading ");
            
            #line default
            #line hidden
            
            #line 42 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( entityClassName ));
            
            #line default
            #line hidden
            
            #line 42 ""
            this.Write(" {action.Id}...\");\n                var ");
            
            #line default
            #line hidden
            
            #line 43 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( localEntity ));
            
            #line default
            #line hidden
            
            #line 43 ""
            this.Write("Response = await ");
            
            #line default
            #line hidden
            
            #line 43 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( entityClassName ));
            
            #line default
            #line hidden
            
            #line 43 ""
            this.Write(".GetAsync(action.Id);\n\n                _logger.LogInformation($\"");
            
            #line default
            #line hidden
            
            #line 45 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( entityClassName ));
            
            #line default
            #line hidden
            
            #line 45 ""
            this.Write(" {action.Id} loaded successfully!\");\n                dispatcher.Dispatch(new Load" +
                    "");
            
            #line default
            #line hidden
            
            #line 46 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( entityClassName ));
            
            #line default
            #line hidden
            
            #line 46 ""
            this.Write("DetailSuccessAction(");
            
            #line default
            #line hidden
            
            #line 46 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( localEntity ));
            
            #line default
            #line hidden
            
            #line 46 ""
            this.Write("Response));\n            }\n            catch (Exception e)\n            {\n         " +
                    "       _logger.LogError($\"Error loading ");
            
            #line default
            #line hidden
            
            #line 50 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( entityClassName ));
            
            #line default
            #line hidden
            
            #line 50 ""
            this.Write(" {action.Id}, reason: {e.Message}\");\n                dispatcher.Dispatch(new Load" +
                    "");
            
            #line default
            #line hidden
            
            #line 51 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( entityClassName ));
            
            #line default
            #line hidden
            
            #line 51 ""
            this.Write("DetailFailureAction(e.Message));\n            }                \n");
            
            #line default
            #line hidden
            
            #line 53 ""

    } /* end Load */
    else if (crud == "Create") {

            
            #line default
            #line hidden
            
            #line 57 ""
            this.Write("           try\n            {\n                _logger.LogInformation($\"Creating ");
            
            #line default
            #line hidden
            
            #line 59 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( entityClassName ));
            
            #line default
            #line hidden
            
            #line 59 ""
            this.Write(" {action.");
            
            #line default
            #line hidden
            
            #line 59 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( entityClassName ));
            
            #line default
            #line hidden
            
            #line 59 ""
            this.Write("}...\");\n                var createdEntity = await action.");
            
            #line default
            #line hidden
            
            #line 60 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( entityClassName ));
            
            #line default
            #line hidden
            
            #line 60 ""
            this.Write(".StoreAsync();\n\n                _logger.LogInformation(\"");
            
            #line default
            #line hidden
            
            #line 62 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( entityClassName ));
            
            #line default
            #line hidden
            
            #line 62 ""
            this.Write(" created successfully!\");\n                dispatcher.Dispatch(new Create");
            
            #line default
            #line hidden
            
            #line 63 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( entityClassName ));
            
            #line default
            #line hidden
            
            #line 63 ""
            this.Write("SuccessAction(createdEntity));\n            }\n            catch (Exception e)\n    " +
                    "        {\n                _logger.LogError($\"Could not create todo, reason: {e.M" +
                    "essage}\");\n                dispatcher.Dispatch(new Create");
            
            #line default
            #line hidden
            
            #line 68 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( entityClassName ));
            
            #line default
            #line hidden
            
            #line 68 ""
            this.Write("FailureAction(e.Message));\n            }\n");
            
            #line default
            #line hidden
            
            #line 70 ""

    }  /* end Create */
    else if (crud == "Update" ) {

            
            #line default
            #line hidden
            
            #line 74 ""
            this.Write("            try\n            {\n                _logger.LogInformation($\"Updating t" +
                    "odo {action.Id}...\");\n                var updatedEntity = await action.");
            
            #line default
            #line hidden
            
            #line 77 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( entityClassName ));
            
            #line default
            #line hidden
            
            #line 77 ""
            this.Write(".StoreAsync();\n               \n                dispatcher.Dispatch(new ");
            
            #line default
            #line hidden
            
            #line 79 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( crud ));
            
            #line default
            #line hidden
            
            #line 79 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( entityClassName ));
            
            #line default
            #line hidden
            
            #line 79 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( actionType ));
            
            #line default
            #line hidden
            
            #line 79 ""
            this.Write("SuccessAction(updatedEntity));\n            }\n            catch (Exception e)\n    " +
                    "        {\n                _logger.LogError($\"Could not update todo, reason: {e.M" +
                    "essage}\");\n                dispatcher.Dispatch(new ");
            
            #line default
            #line hidden
            
            #line 84 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( crud ));
            
            #line default
            #line hidden
            
            #line 84 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( entityClassName ));
            
            #line default
            #line hidden
            
            #line 84 ""
            this.Write("FailureAction(e.Message));\n            }\n");
            
            #line default
            #line hidden
            
            #line 86 ""

    }  /* end Update */
    else if (crud == "Delete" )  {

            
            #line default
            #line hidden
            
            #line 90 ""
            this.Write("            try\n            {\n                _logger.LogInformation($\"Deleting t" +
                    "odo {action.Id}...\");\n                var droppedEntity = await action.");
            
            #line default
            #line hidden
            
            #line 93 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( entityClassName ));
            
            #line default
            #line hidden
            
            #line 93 ""
            this.Write(".DropAsync();\n               \n                dispatcher.Dispatch(new ");
            
            #line default
            #line hidden
            
            #line 95 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( crud ));
            
            #line default
            #line hidden
            
            #line 95 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( entityClassName ));
            
            #line default
            #line hidden
            
            #line 95 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( actionType ));
            
            #line default
            #line hidden
            
            #line 95 ""
            this.Write("SuccessAction(droppedEntity));\n            }\n            catch (Exception e)\n    " +
                    "        {\n                _logger.LogError($\"Could not update todo, reason: {e.M" +
                    "essage}\");\n                dispatcher.Dispatch(new ");
            
            #line default
            #line hidden
            
            #line 100 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( crud ));
            
            #line default
            #line hidden
            
            #line 100 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( entityClassName ));
            
            #line default
            #line hidden
            
            #line 100 ""
            this.Write("FailureAction(e.Message));\n            }\n");
            
            #line default
            #line hidden
            
            #line 102 ""
 
    } /* end else */ 
 } /* end actionype */ 
 else if (actionType == "Success") { 
 
            
            #line default
            #line hidden
            
            #line 107 ""
            this.Write("\n    _logger.LogInformation(\"");
            
            #line default
            #line hidden
            
            #line 108 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( crud ));
            
            #line default
            #line hidden
            
            #line 108 ""
            this.Write(" ");
            
            #line default
            #line hidden
            
            #line 108 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( entityClassName ));
            
            #line default
            #line hidden
            
            #line 108 ""
            this.Write(" successfully, navigating back to todo listing...\");\n    \n    /*\n        Write co" +
                    "de for navigating back here\n    */\n\n    return Task.CompletedTask;\n");
            
            #line default
            #line hidden
            
            #line 115 ""
 } /* end if */ 
            
            #line default
            #line hidden
            
            #line 116 ""
            this.Write(" \n        }\n    }\n}\n`");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class EffectTemplateBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
